[Feature/domain modeling] Basic Domain Structure, Table Modeling
wafflestudio19-5/team1-server pull request #10
Opened 2021-12-10 02:48 UTC by moonpiderman

기본적인 도메인 구조 생성 및 모델링 완료하였습니다!
‼️**해당 브랜치는 `feature/UserLogin` 브랜치에서 따왔습니다.**‼️

### 고민
`VoteStatus`를 Enum Class로 생성하였는데 투표값을 어떻게 매겨줄지에 대해 생각해봤습니다.
서비스 로직에서 `VoteStatus`를 사용해서 값을 주는 게 맞지 않을까하여 `Vote` 테이블에서 `status` 부분은 오히려 `Integer`형태가 맞지 않을까 하는 고민이 들었습니다!

아래 `DataGrip`이 생성해준 다이어그램 첨부해드릴테니 참고하시면 좋을듯합니다!
![image](https://user-images.githubusercontent.com/70942197/145508752-4f98c975-a627-4840-9ae5-9ea84dba9115.png)

2021-12-11 09:39 UTC, yg-moon commented on src/main/kotlin/com/wafflestudio/waffleoverflow/domain/question/model/QuestionTag.kt
> +) : BaseEntity()
생성시점 기록이 필요없는 모델은 BaseEntity를 상속하신 것도 좋은 것 같습니다.

2021-12-11 09:41 UTC, yg-moon commented on src/main/kotlin/com/wafflestudio/waffleoverflow/domain/vote/model/Vote.kt
> +    // Isn't it constant value?
이 부분은 말씀드린대로 중복투표를 방지하기 위해 유저마다 하나씩 투표 객체를 갖고 있는 식으로 구현하여, 각 question마다 up down의 격차를 계산 후 프론트에 결과를 주는 식으로 하면 될 것 같습니다.

2021-12-11 09:43 UTC, yg-moon commented
연관관계도 모두 잘 되어있고, fetchType Lazy 같은 부분들도 꼼꼼히 처리해주셨네요. 한눈에 보기 좋게 Datagrip 다이어그램까지 올려주시고, 고생하셨습니다!

2021-12-11 09:43 UTC, yg-moon approved these changes
LGTM

2021-12-11 10:14 UTC, moonpiderman commented on src/main/kotlin/com/wafflestudio/waffleoverflow/domain/question/model/QuestionTag.kt
> +) : BaseEntity()
감사합니다! 딱 아셨네요

2021-12-12 14:10 UTC, caelum02 requested changes
코드 깔끔한 것 같습니다. `CascadeType`은 일단 전부 `All`로 설정해두신 건가요?

2021-12-13 03:27 UTC, moonpiderman commented
@caelum02 내 전부 CascadeType.ALL로 설정해두었습니다!

2021-12-13 03:28 UTC, merged